### ISSUE TITLE
[BUG] [INSTALLATION ERROR][TRAVIS] Install fails

### ISSUE THREAD

**Issue by chaithyagr** [CEA-COSMIC/pysap#114]
**System setup**
OS: [e.g] macOS v10.14.1
Python version: All
Python environment (if any): [e.g.] conda v4.5.11 / Venv

**Describe the bug**
A `python setup.py install` is broken with at build_ext task:
```
running build_ext
Traceback (most recent call last):
  File "setup.py", line 198, in <module>
    "test": HybridTestCommand
  File "/home/chaithyagr/Envinronments/testenv/lib/python3.5/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/chaithyagr/Envinronments/testenv/lib/python3.5/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/chaithyagr/Envinronments/testenv/lib/python3.5/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/chaithyagr/Envinronments/testenv/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/chaithyagr/Envinronments/testenv/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/chaithyagr/Envinronments/testenv/lib/python3.5/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib/python3.5/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 90, in run
    self._preinstall(preinstall_list)
  File "setup.py", line 74, in _preinstall
    pip_main(['install'] + options + package_list)
TypeError: 'module' object is not callable

```

**To Reproduce**
On a new conda or venv try:
`python setup.py install`
or 
`pip install git+https://github.com/CEA-COSMIC/pysap`

**Expected behavior**
For installation to run smoothly

**Module and lines involved**
This is something recent that popped up just yesterday, note that pip 19.3 was recently released (14th October). This is causing errors while installing pybind11 at line 74. This needs to be changed

https://github.com/CEA-COSMIC/pysap/blob/ffc5ee9dfde8dfb1a67b06de3c6eeae9d8f99993/setup.py#L67-L74

**Are you planning to submit a Pull Request?**
- [X] Yes
- [ ] No

**Comment by sfarrens** [comment]
This issue only appears to affect Python v3.7.3. The line that needs fixing is [26](https://github.com/CEA-COSMIC/pysap/blob/ffc5ee9dfde8dfb1a67b06de3c6eeae9d8f99993/setup.py#L26).

This patch worked for me:

```python
try:
    from pip import main as pip_main
except ImportError:
    from pip._internal import main as pip_main
    if not callable(pip_main):
        pip_main = pip_main.main
```

**Comment by chaithyagr** [comment]
It affects all versions that have pip 19.3 or above. 

I have a PR for this #115 . I have removed the first try statement as it makes no sense in supporting something which is very old version of pip. Also, I support pip<=19.3 with a deprecation warning that this will cause errors in future.

**Comment by chaithyagr** [comment]
I think this can be closed. Please reopen if there are still issues
